sudo: false
language: node_js
node_js:
- iojs
- '0.12'
- '0.10'
before_install: npm install -g grunt-cli
install: npm install
before_script: grunt
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
